stages:
  - deploy

local-hostshell:
  stage: deploy
  tags:
    - shell  # Matches the tag used by your GitLab runner
  script:
    # Load kubeconfig from base64 env variables
    - echo "$KUBECONFIG_B64" | base64 -d > kubeconfig
    - export KUBECONFIG=$PWD/kubeconfig

    # Confirm Kubernetes access
    - echo "Confirming Kubernetes cluster connectivity..."
    - kubectl get nodes
    - kubectl get pods -A

    # Start deployment
    - echo "Starting CNAS deployment..."
    - chmod +x charts/deploy-all.sh
    - ./charts/deploy-all.sh
  only:
    - main
