apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service
  namespace: cnas-crud-php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: query-service
  template:
    metadata:
      labels:
        app: query-service
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nslookup mysql.cnas-crud-php.svc.cluster.local; do echo waiting for mysql; sleep 2; done']
      containers:
      - name: query-service
        image: mrdocker123x3/query-service:latest
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DB_NAME
          value: mydb
        ports:
        - containerPort: 80
