version: '3.8'

services:
  gitlab-server:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab-server
    ports:
      - '8088:80'
    environment:
      GITLAB_ROOT_EMAIL: "${GITLAB_ROOT_EMAIL}"
      GITLAB_ROOT_PASSWORD: "${GITLAB_ROOT_PASSWORD}"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/data:/var/opt/gitlab
    restart: always