# .github/workflows/build-and-scan-trivy
name: Build, Push, and Scan with Trivy

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/my-app:latest

jobs:
  build-push-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .

    - name: Push Docker image
      run: docker push $IMAGE_NAME

    - name: Install Trivy
      uses: aquasecurity/trivy-action@v0.16.1

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@v0.16.1
      with:
        image-ref: ${{ env.IMAGE_NAME }}
        format: table
        exit-code: 1
        ignore-unfixed: true
