name: Build, Push, and Scan All Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  build-push-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: php-app
            context: ./cnas2/php-app
          - name: nginx
            context: ./cnas2/nginx
          - name: mysql
            context: ./cnas2/mysql

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image - ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/cnas-${{ matrix.name }}:latest

      - name: Scan image with Trivy - ${{ matrix.name }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/cnas-${{ matrix.name }}:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
