#/.github/workflows/build-and-scan-trivy.yml
name: Build, Push, and Scan with Trivy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/cnas_project:latest

jobs:
  build-push-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}

    - name: Trivy Scan - Docker image
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: ${{ env.IMAGE_NAME }}
        format: table
        exit-code: 1
        ignore-unfixed: true
        vuln-type: "os,library"

    - name: Trivy Scan - Filesystem (IaC/Secrets/Vuln)
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: fs
        scan-ref: .
        format: table
        exit-code: 1

    - name: Trivy Scan - Dockerfile
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: config
        scan-ref: ./Dockerfile
        format: table
        exit-code: 1
