name: Build and Scan Docker Images with Trivy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: php-app
            context: ./php-app
            tag: cnas-php-app
          - name: nginx
            context: ./nginx
            tag: cnas-nginx-proxy
          - name: mysql
            context: ./mysql
            tag: cnas-mysql-db

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image - ${{ matrix.name }}
        run: docker build -t ${{ matrix.tag }}:local ${{ matrix.context }}

      - name: Run Trivy vulnerability scan - ${{ matrix.name }}
        run: |
          trivy image \
            --format table \
            --output trivy-report-${{ matrix.name }}.txt \
            --exit-code 1 \
            --ignore-unfixed \
            --vuln-type os,library \
            ${{ matrix.tag }}:local

      - name: Upload Trivy report artifact - ${{ matrix.name }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report-${{ matrix.name }}
          path: trivy-report-${{ matrix.name }}.txt
