name: CI – Build, Test & Push All Services

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKERHUB_NAMESPACE: asyiqan
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push MySQL Init Image
        run: |
          docker build -t $DOCKERHUB_NAMESPACE/cnas-mysql-db:${IMAGE_TAG} ./mysql
          docker push   $DOCKERHUB_NAMESPACE/cnas-mysql-db:${IMAGE_TAG}

      - name: Build, Test & Push PHP + NGINX Services
        run: |
          docker network create test-net || true

          for svc in php-app nginx; do
            img="$DOCKERHUB_NAMESPACE/cnas-$svc"

            echo "==> Building $svc"
            docker build -t $img:${IMAGE_TAG} "./$svc"

            echo "==> Starting MySQL for $svc test"
            docker run -d --name mysql-test --network test-net \
              -e MYSQL_ROOT_PASSWORD=root \
              -e MYSQL_DATABASE=users \
              mysql:8.0

            echo "==> Waiting for MySQL to be ready"
            for i in {1..10}; do
              docker exec mysql-test mysqladmin ping -h127.0.0.1 -uroot -proot && break
              sleep 5
            done

            echo "==> Testing $svc connectivity"
            docker run --rm --network test-net $img:${IMAGE_TAG} \
              php -r "exit(mysqli_connect('mysql-test','root','root','users') ? 0 : 1);"

            echo "==> Pushing $img:${IMAGE_TAG}"
            docker push $img:${IMAGE_TAG}

            docker rm -f mysql-test || true
          done
