name: Build, Test, and Push All Services
# HEHE HAHA
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: users
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build php-app
      run: docker build -t asyiqan/cnas-php-app:latest ./php-app

    - name: Build nginx
      run: docker build -t asyiqan/cnas-nginx-proxy:latest ./nginx

    - name: Build mysql
      run: docker build -t asyiqan/cnas-mysql-db:latest ./mysql

    - name: Test PHP App ↔ MySQL
      run: |
        docker network create test-net
        docker run -d --name mysql-test --network test-net -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=users mysql:8.0
        sleep 20
        docker build -t test-php ./php-app
        docker run --rm --network test-net test-php php -r "echo mysqli_connect('mysql-test', 'root', 'root', 'users') ? '✅ Connected' : '❌ Failed';"

    - name: Push php-app
      run: docker push asyiqan/cnas-php-app:latest

    - name: Push nginx
      run: docker push asyiqan/cnas-nginx-proxy:latest

    - name: Push mysql
      run: docker push asyiqan/cnas-mysql-db:latest
