name: Dockerfile Lint

on:
  push:
    paths:
      - '**/Dockerfile'  # triggers on any Dockerfile anywhere
  pull_request:
    paths:
      - '**/Dockerfile'
  workflow_dispatch:  # <-- This enables the manual run button

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Dockerfiles recursively
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
