# .github/workflows/phpmd.yml
name: PHPMD Static Analysis

on:
  push:
    branches: [main]
  pull_request:

jobs:
  phpmdbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2   # <== Use v2 here instead of v3
        with:
          php-version: '8.2'
      - name: Run PHPMD
        run: phpmd src text cleancode,codesize,controversial,design,naming,unusedcode

