# .github/workflows/phpmd.yml
name: PHPMD Static Analysis

on:
  push:
    branches: [main]
  pull_request:

jobs:
  phpmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Run PHPMD
        run: vendor/bin/phpmd src text cleancode,codesize,unusedcode
