- name: Run Psalm on all PHP microservices
  run: |
    for dir in services/*-service; do
      echo "==> Running Psalm in $dir"

      curl -sSL https://github.com/vimeo/psalm/releases/latest/download/psalm.phar -o "$dir/psalm.phar"
      chmod +x "$dir/psalm.phar"

      cd "$dir"

      if [ ! -f psalm.xml ] && [ ! -f psalm.xml.dist ]; then
        echo "⚠️ No Psalm config found in $dir, initializing..."
        php psalm.phar --init --no-progress
      fi

      ./psalm.phar --show-info=true || {
        echo "❌ Psalm found issues in $dir"
        exit 1
      }

      echo "✅ Psalm passed for $dir"
      cd - > /dev/null
    done
