name: Psalm PHP Static Analysis

on:
  push:
    branches: [main]
  pull_request:

jobs:
  psalm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Run Psalm on all PHP microservices
      run: |
        for dir in services/*-service; do
          echo "==> Running Psalm in $dir"

          # Download Psalm PHAR inside each service folder
          curl -sSL https://github.com/vimeo/psalm/releases/latest/download/psalm.phar -o "$dir/psalm.phar"
          chmod +x "$dir/psalm.phar"

          cd "$dir"

          # Initialize config if none exists, specifying current folder as source
          if [ ! -f psalm.xml ] && [ ! -f psalm.xml.dist ]; then
            echo "⚠️ No Psalm config found in $dir, initializing..."
            php psalm.phar --init .
          fi

          # Run Psalm without extra flags (avoid unsupported flags)
          ./psalm.phar --show-info=true || {
            echo "❌ Psalm found issues in $dir"
            exit 1
          }

          echo "✅ Psalm passed for $dir"
          cd - > /dev/null
        done
