# .github/workflows/psalm.yml
name: Psalm PHP Static Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  psalm:
    name: Run Psalm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2  # ✅ CORRECT VERSION
        with:
          php-version: '8.2'
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Psalm
        run: vendor/bin/psalm

